dist: trusty
sudo: required
group: beta
language: node_js
node_js:
- '8'
matrix:
  fast_finish: true
cache:
  directories:
  - node_modules
notifications:
  slack:
    rooms:
      secure: A7JJDEdIHzZ3npk3BrVqHh+ZHT0fVjOSAdMk8G4Ct+ZfmL4rCPB/W+zCI9HQYyIoOQ8fLKITMR5DUJwNVxCo2+K5ciRQ/UgNov0eoMbX11W6NNvX+qVDQY7qplilBhw62laqJxWlFOy97cvxiJTTRnXAR5AD0h4mtWzoYeloOx0VreFQ9ZDMQkzIou9YkT6MQvnwD1bRUM70Iavz22DZxTSGvId4RN9IMAR5ornKFBb4ysxegvBPK6KQbTC8Ioj7/aLO3cCoavo4516cDu2Fi2zN6eqpQMHOlWDXA8BlCQmW4iuoStUCol7++d2N+HVVSrzEB8WjVDbA/+dnNeK04eROvLxwFTzbOXHmp4CrX1NPN1EMGKtPa7Q0E0kkhwk0hsNqqatwWI8i7axyLsSlBua65/i1Cs4D0GJ+rRLkEm/EzDTIjf/J3W4vecyrgvUgr8/amzmiTCNlcLMhDesgoQWuhSWMEmIRTGSGTfXJDg3W2CCO1O4EM1tyC+z1LU1eUKtJHVFZM7xqdZEHnLerByY/t0jg8USWdPrR+8JAAvKoX+udAp1Dfz/+CYZ29Aw43pUHmB7M93y8TetTFLseWYWOqWl8ehZl0l2ZvheNGu7altHJvsO8ITYJkVQi09MsgL7S0SEyxKNlD/5LRCUCcavR9sbTTNdikqLcAb9o5Fc=
    template:
    - ":hammer_and_wrench: Build <%{build_url}|#%{build_number}> %{result} in %{duration}\n :octocat: <https://www.github.com/%{repository_slug}/tree/%{branch}|%{repository_slug}@%{branch}> in PR <%{pull_request_url}|#%{pull_request_number}>\n:scroll: (<%{compare_url}|%{commit}>) - _%{commit_message}_\n:godmode: %{author}"    